const urlParams = new URLSearchParams(window.location.search);
const id = urlParams.get("id");
  
if (id) {
    console.log(id)
    fetch(`points/${id}.txt`)
    .then((response) => response.text())
    .then((data) => {
        paragraphs = data.split("\n\n");
        const template = document.getElementById("template");
        template.innerHTML = `
        <h1>${id}</h1>
        ${paragraphs.map((p) => `<p>${p}</p>`).join("")}
        <div class="baguetteBoxOne">
            <figure>
                <a href="images/${id}.png">
                    <img src="images/${id}.png">
                </a>
                <figcaption>Image generated by Stable Diffusion XL</figcaption>
            </figure>
        </div>
        `;
    })
    .catch((error) => console.error("Error fetching data:", error));
}